# Generated by Django 3.2 on 2021-11-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_of_birth',
            new_name='data_urodzenia',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='zdjęcie',
        ),
    ]
